### ISSUE TITLE
Q: Deriving sum types?

### ISSUE THREAD

**Issue by ocramz** [mkloczko/derive-storable#3]
Are there any workarounds to derive Storable for sum types?

**Comment by mkloczko** [comment]
Unfortunately, at the moment no. We'd need to implement tags for sum types, but they come with design decisions I'm not sure about (tag placement, making it correspond to C code with help of user input)

**Comment by poscat0x04** [comment]
If you only want to store Haskell values in memory, you can use one tag per `:+:` (tho there will be some overhead).
If you need to generate Storable instances for Haskell sum types that represent C enums you can just cast the pointer to `Ptr CInt` and convert back. The instance declaration should be relatively simple and can be easily automated with TH.

**Comment by mkloczko** [comment]
Thank you for the suggestions. It should be possible to use Type Funs to create one tag by processing the generic rep tree. 

Just wondering whether this should be default option or not (as in, this still forces a certain design on C-side of things). I'm thinking whether or not to add a sumtype flag in order to toggle this functionality. 

EDIT: Just in case [here's](https://github.com/mkloczko/derive-storable/blob/typefuns/src/Foreign/Storable/Generic/Tools.hs) an example of type functions in action.

**Comment by mkloczko** [comment]
Done'ish.
